name: build_flutter
on: workflow_dispatch
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.13.0
          channel: stable
      - run: flutter --version
  check-settings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: flutter-action
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          echo CACHE-PATH=${{ steps.flutter-action.outputs.CACHE-PATH }}
          echo CACHE-KEY=${{ steps.flutter-action.outputs.CACHE-KEY }}
          echo CHANNEL=${{ steps.flutter-action.outputs.CHANNEL }}
          echo VERSION=${{ steps.flutter-action.outputs.VERSION }}
          echo ARCHITECTURE=${{ steps.flutter-action.outputs.ARCHITECTURE }}
        shell: bash